# Generated by Django 5.2.7 on 2025-10-07 04:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('trigger_probability', models.FloatField(default=0.1)),
            ],
        ),
        migrations.CreateModel(
            name='FakeSystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('VIRUS', 'Fake Virus Warning'), ('UPDATE', 'Unnecessary Update'), ('STORAGE', 'Fake Storage Full'), ('SECURITY', 'Fake Security Breach'), ('PERFORMANCE', 'Fake Performance Issue')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('fake_urgency_level', models.IntegerField(default=8)),
                ('requires_immediate_action', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('user_satisfaction', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from_bot', models.BooleanField(default=True)),
                ('message_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('was_helpful', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.chatbotconversation')),
            ],
        ),
        migrations.CreateModel(
            name='PopupEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('popup_type', models.CharField(choices=[('AD', 'Fake Advertisement'), ('SURVEY', 'Pointless Survey'), ('NOTIFICATION', 'Useless Notification'), ('OFFER', 'Terrible Offer'), ('WARNING', 'Fake System Warning'), ('CHATBOT', 'Annoying Chatbot')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Mildly Annoying'), ('MEDIUM', 'Moderately Irritating'), ('HIGH', 'Extremely Obnoxious'), ('CRITICAL', 'Absolutely Infuriating')], default='MEDIUM', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_interaction', models.BooleanField(default=True)),
                ('auto_close_seconds', models.IntegerField(blank=True, null=True)),
                ('fake_urgency', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='UserEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SHOWN', 'Event Displayed'), ('CLICKED', 'User Clicked'), ('DISMISSED', 'User Dismissed'), ('IGNORED', 'User Ignored'), ('RAGED_QUIT', 'User Rage Quit')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_reaction_time', models.FloatField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('popup_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.popupevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
